# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=250)),
                ('assigned_to', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
